events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        location / {
            # 🚨 แก้ไขชื่อตรงนี้เป็น ced-web ครับ
            proxy_pass http://ced-web:3000/reqform/;
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}